const URL =
  window.location.hostname === `localhost`
    ? `http://localhost:4000`
    : `http://164.90.180.49`;

const NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "ckellytv";
const NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "dzxujvsk";
const NEXT_PUBLIC_CLOUDINARY_KEY = "884113981828137";
const CLOUDINARY_SECRET = "lMAtVMwjbTz-mPc7udjQStS4I_E";

export {
  URL,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
  NEXT_PUBLIC_CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
};
